apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: socketcluster2
  name: scc-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scc-worker
  template:
    metadata:
      labels:
        component: scc-worker
    spec:
      containers:
        - env:
            - name: SCC_STATE_SERVER_HOST
              value: scc-state
            - name: SCC_INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ENV
              value: prod
          image: 'socketcluster/socketcluster:v16.0.1'
          livenessProbe:
            httpGet:
              path: /health-check
              port: scc-worker
            initialDelaySeconds: 15
            timeoutSeconds: 20
          name: scc-worker
          ports:
            - containerPort: 8000
              name: scc-worker
          readinessProbe:
            httpGet:
              path: /health-check
              port: scc-worker
            initialDelaySeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /usr/src/app
              name: app-src-volume
      initContainers:
        - command:
            - cp
            - '-a'
            - /usr/src/.
            - /usr/dest/
          name: app-src-container
          image: 'jorritjdjict/socketcluster-sample:v1.0.9'
          volumeMounts:
            - mountPath: /usr/dest
              name: app-src-volume
      volumes:
        - emptyDir: {}
          name: app-src-volume
